steps:
# Build and push the docker
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/rabbitmq:$TAG_NAME'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/rabbitmq:$TAG_NAME'
# Get kube credentials manualy
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'config'
  - 'set'
  - 'container/use_v1_api_client'
  - 'false'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '--region=us-central1'
  - 'heili-us-central1'
# Deploy ot Heili cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - rabbitmq
  - rabbitmq=gcr.io/$PROJECT_ID/rabbitmq:$TAG_NAME
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=heili-us-central1'
images:
- 'gcr.io/$PROJECT_ID/rabbitmq:$TAG_NAME'
